name: Run
on:
  schedule:
    - cron: '0 */6 * * *'
env:
  INSTARGRAM_USERNAME: ${{ secrets.INSTARGRAM_USERNAME }}
  INSTARGRAM_PASSWORD: ${{ secrets.INSTARGRAM_PASSWORD }}
  OTP_SECRET: ${{ secrets.OTP_SECRET }}
  SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
  SCHOOL_REGION: ${{ secrets.SCHOOL_REGION }}
jobs:
  gradle:
#    strategy:
#      matrix:
#        os: [ ubuntu-latest ]
#    runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew run
